gunnum = int(input("จำนวนปืนที่รับมา "))
cost = float(input("รับมากระบอกละกี่บาท "))
sell = float(input("ราคาขายต่อ "))
team = int(input("ลูกน้องกี่คน "))
oricost = (gunnum * cost)
orisell = (gunnum * sell)
sellup = (orisell-oricost)
boss = (sellup / 20)
teamsell = (sellup - boss) / team
print("ต้นทุน ",orisell)
print("รายรับ ",oricost)
print("กำไร ",sellup)
print("เงินที่บอสได้ ",boss)
print("เงินที่ลูกน้องได้ ",teamsell)